### ISSUE TITLE
Wrong paths on Arch Linux / AUR

### ISSUE THREAD

**Issue by plntyk** [Aetf/kmscon#10]
Installing on Arch Linux via AUR (kmscon-patched-git, libtsm-patched-git) now does not work anymore 
after latest change #9 

running kmscon does not work because /usr/bin/kmscon contains the wrong path

AUR package creates a 
````
/usr/lib/kmscon/kmscon/kmscon
````
Editing AUR configure options and/or kmscon shellscript that calls the binary manually fixed the situation so that for example systemctl start kmscon works again

**Comment by Aetf** [comment]
Sorry for the careless fix :P 

I've updated both the PKGBUILD and `scripts/kmscon` to be consistent with the path change.

Could both of you @plntyk @PegasusEpsilon test before I close this?

**Comment by LChris314** [comment]
Not those two users but I've just updated and it worked fine. File list shown by `pacman -Ql` shows correct path.

**Comment by plntyk** [comment]
Uninstalled and reinstalled kmscon-patched-git via AUR and it works.

**Comment by Aetf** [comment]
Okay. I'm closing this then. Fixed in d2c013411a14f05e298c0bfa6f469913bcc5d289

**Comment by PegasusEpsilon** [comment]
Sorry for the delay, can confirm that this has been fixed. Thanks, @Aetf!

**Comment by Aetf** [comment]
@PegasusEpsilon Cool!
