### ISSUE TITLE
INSTALL: Cannot find shared object file libtsm.so.4

### ISSUE THREAD

**Issue by tecfu** [Aetf/kmscon#16]
I downloaded and installaed libtsm 4 from https://github.com/Aetf/libtsm via the following but kmscon doesn't see to find it:

```
$ git clone https://github.com/Aetf/libtsm
$ cd libstsm
$ test -f ./configure || NOCONFIGURE=1 ./autogen.sh
$ ./configure
$ make
$ make install
```

OS:
Ubuntu Server 18.04

ERROR:
```
$ kmscon

/usr/local/libexec/kmscon/kmscon: error while loading shared libraries: libtsm.so.4: cannot open shared object file: No such file or directory
```
NOTES:
```
$ ls /usr/local/lib

kmscon
libtsm.a
libtsm.la
libtsm.so
libtsm.so.4
libtsm.so.4.0.0
node_modules
pkgconfig
python2.7
python3.6
```

**Comment by tecfu** [comment]
This is the output of make check:

```
$ make check

tests/test_input.c:39:10: fatal error: X11/keysym.h: No such file or directory
 #include <X11/keysym.h>
          ^~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [tests/test_input-test_input.o] Error 1
make[1]: *** [check-am] Error 2
make: *** [check-recursive] Error 1
```

**Comment by tecfu** [comment]
Temporary Fix: 

```
$ LD_LIBRARY_PATH=/usr/local/lib
$ export LD_LIBRARY_PATH
$ kmscon
```

**Comment by plntyk** [comment]
I dont think that this is a bug because /usr/local is a common path for manually / user compiled software and libraries.

Using 
````-prefix=/usr```` like in arch AUR
or changing paths / environment variables are valid solutions too.

**Comment by tecfu** [comment]
@plntyk Let's document this then, instead of placing the burden on the user to make the fix.

**Comment by Aetf** [comment]
I agree with @plntyk that this is not a bug but a common practice for manually compiled software. But more documentation is always better.

I saw your pull request #15 to add that documentation, so let's move the discussion there.
