### ISSUE TITLE
Build failures on recent arch

### ISSUE THREAD

**Issue by GeoffreyRobert** [Aetf/kmscon#25]
I can't paste the error logs since I don't have X or whatever on the build machine.
Systemd dependency not detected: libsystemd-{daemon,login} merged into libsystemd (configure.ac)
SIGUNUSED undeclared compilation error: due to glibc>=2.26 -> https://stackoverflow.com/a/51468191/12126213 (src/pty.c)
minor / major linking error: found a patch here https://github.com/Ebiroll/qemu_esp32/issues/12 (src/uterm_vt.c)

Sorry for the formatting. Thanks for maintaining this

**Comment by Aetf** [comment]
I see no build errors and `SIGUNUSED` has long been removed. Are you sure you are building using sources from this repo?
