### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by viccie30** [Aetf/kmscon#42]
[Your fork of libtsm was finally uploaded to Debian](https://tracker.debian.org/news/1321254/accepted-libtsm-402-01-source-i386-into-unstable-unstable/), so I can start on getting kmscon uploaded as well. 

Would it be possible to make a new release containing all improvements since version 8? I personally don't mind whether #40 and #41 are included or not, but it would be good if they can be of course.

**Comment by Aetf** [comment]
> Your fork of libtsm was finally uploaded to Debian, so I can start on getting kmscon uploaded as well.

Really appreciate your effort on packaging this!

I think I can do a new release after #40.

**Comment by viccie30** [comment]
Thanks for the new release! I'll see if I can do the Debian packaging later this week.
