### ISSUE TITLE
libdrm dependency

### ISSUE THREAD

**Issue by viccie30** [Aetf/kmscon#48]
The dependency on `libdrm` is added twice in `meson.build`. Once unconditionally (https://github.com/Aetf/kmscon/blob/32927918cf5f90c2219d4f17055f9a9aef5223d2/meson.build#L50) and once conditioned on either `video_drm2d` or `video_drm3d` being enabled (https://github.com/Aetf/kmscon/blob/32927918cf5f90c2219d4f17055f9a9aef5223d2/meson.build#L65-L68). A few lines down (https://github.com/Aetf/kmscon/blob/32927918cf5f90c2219d4f17055f9a9aef5223d2/meson.build#L93-L94) the requirement is checked for `video_drm3d`, but not for `video_drm2d`.

In 'src/meson.build' the dependency is added for both `video_drm2d` or `video_drm3d` again (https://github.com/Aetf/kmscon/blob/32927918cf5f90c2219d4f17055f9a9aef5223d2/src/meson.build#L115-L118).

I don't know exactly what the dependency is supposed to be, but I think all four places need to be aligned.

**Comment by Aetf** [comment]
Ah, it was like this in the original autotools scripts. I noticed it while I more or less directly translating from autotools to meson, but then forgot to fix it.

Nice catch, I will take a look today or tomorrow.

**Comment by viccie30** [comment]
The joys of inherited autotools scripts.
