### ISSUE TITLE
Read layout from `/etc/vconsole.conf`

### ISSUE THREAD

**Issue by Diegovsky** [Aetf/kmscon#51]
I think that's what getty does and it would improve compatibility with the system a bit

Here's a man page from Arch Linux describing what it does: [vconsole.conf](https://man.archlinux.org/man/vconsole.conf.5)

**Comment by viccie30** [comment]
Kmscon already gets the layout information from systemd-localed, if available (https://github.com/Aetf/kmscon/blob/develop/scripts/kmscon.in).

**Comment by Diegovsky** [comment]
For some reason all the queries are returning empty results, except for VConsoleKeymap. Apparently localectl didn't set my xkb keymap, but I fixed it now. Thank you :)
