### ISSUE TITLE
Errors on building because of missing 

### ISSUE THREAD

**Issue by vanfanel** [Aetf/kmscon#64]
Hi there,

First of all, thanks a lot for keeping KMSCON alive!! I was very glad to find that this is still being working on.

I am trying to build on GNU/Linux Debian 11 on aarch64, and I see this on the building process, which then fails:
```

../src/kmscon_terminal.c: In function ‘kmscon_terminal_register’:
../src/kmscon_terminal.c:627:2: error: implicit declaration of function ‘tsm_vte_set_backspace_sends_delete’ [-Werror=implicit-function-declaration]
  627 |  tsm_vte_set_backspace_sends_delete(term->vte,
      |  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Any idea on what's going on? 

Thanks!

**Comment by vanfanel** [comment]
Note I could pass `-Wno-error` to the compiler, but then I get:
```

/usr/bin/ld: src/kmscon.p/kmscon_terminal.c.o: in function `kmscon_terminal_register':
kmscon_terminal.c:(.text.kmscon_terminal_register+0x128): undefined reference to `tsm_vte_set_backspace_sends_delete'
```

**Comment by viccie30** [comment]
I'm the maintainer for kmscon in Debian and I think I know what's going on.

The mentioned function was added in https://github.com/Aetf/libtsm/pull/23, which is not yet included in a released (and packaged) version.

You need to either use the released versions in Debian for kmscon and libtsm, or use the current code on git for libtsm, until a new release is made.

**Comment by vanfanel** [comment]
@viccie30 Ahh! I see, I should use the git version of libstm if I'm trying to use the git version of kmscon, then.
It's a no-issue in that case. Thanks a lot! :)
