### ISSUE TITLE
Can antialiasing be disabled with pango?

### ISSUE THREAD

**Issue by grepsuzette** [Aetf/kmscon#73]
I got pretty good result with 
```
font-engine=pango
font-name=Terminus, WenQuanYi Micro Hei Mono
font-size=12
font-dpi=192
```
However since Terminus is a bitmap font, it would look much better if we could disable anti-aliasing. 
Does anybody knows how?

**Comment by CoelacanthusHex** [comment]
Pango should follow your fontconfig configuration. So I think disabling anti-aliasing for Terminus font in fontconfig is enough.

**Comment by grepsuzette** [comment]
Alright! 

I created ~/.config/fontconfig/local.conf with this content:
```xml
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>
    <match target="font">
        <edit mode="assign" name="antialias">
            <bool>false</bool>
        </edit>
    </match>
</fontconfig>
```
Works perfectly, thank you very much.
